-- Germany: Schengen Tourist Visa requirements
insert into visa_requirements (country, visa_type, category, requirement_key, title, description, threshold, recommendation, question_hint, display_order) values
('germany', 'schengen_tourist', 'financial', 'bank_balance', 'Bank Balance', 'Minimum bank balance of 5 lakh INR maintained for last 3 months', '500000', 'It is recommended to show at least 5 lakh INR in your savings account. If your balance is lower, consider showing fixed deposits, mutual fund statements, or a sponsor''s financials.', 'How much balance do you currently have in your bank account?', 1),
('germany', 'schengen_tourist', 'financial', 'income_proof', 'Income Proof', 'Salary slips for last 3 months or ITR for last 2 years', null, 'You''ll need recent salary slips or your Income Tax Returns. If you are self-employed, CA-certified financials work too.', 'Are you salaried or self-employed? Do you have recent salary slips or ITR documents?', 2),
('germany', 'schengen_tourist', 'documents', 'passport_validity', 'Passport Validity', 'Passport must be valid for at least 3 months beyond your planned return date, with at least 2 blank pages', null, 'Your passport needs at least 3 months validity after you return. If it expires sooner, you''ll need to renew it first — which takes about 1-2 weeks.', 'When does your current passport expire? How many blank pages do you have?', 3),
('germany', 'schengen_tourist', 'documents', 'passport_photos', 'Passport Photos', '2 recent passport-size photos (35mm x 45mm, white background, taken within last 6 months)', null, 'You''ll need 2 photos meeting Schengen specifications — 35x45mm, white background, neutral expression. Most photo studios know the specs.', 'Do you have recent passport-size photos that meet Schengen specifications?', 4),
('germany', 'schengen_tourist', 'documents', 'cover_letter', 'Cover Letter', 'A letter explaining the purpose of your visit, travel dates, itinerary, and accommodation details', null, 'I can generate a cover letter for you once we have all your trip details. It should explain why you''re visiting, your exact dates, and where you''re staying.', null, 5),
('germany', 'schengen_tourist', 'documents', 'travel_insurance', 'Travel Insurance', 'Travel medical insurance with minimum coverage of 30,000 EUR, valid for all Schengen states', '30000', 'You need travel insurance covering at least 30,000 EUR for medical emergencies. Companies like ICICI Lombard, Bajaj Allianz, or Tata AIG offer Schengen-compliant policies — usually around 1,000-2,000 INR for a short trip.', 'Do you already have travel insurance, or would you like recommendations?', 6),
('germany', 'schengen_tourist', 'travel', 'flight_booking', 'Flight Booking', 'Confirmed or reserved round-trip flight tickets', null, 'You need a confirmed or tentatively booked return flight. Tip: many airlines and agencies offer "hold" bookings or fully refundable tickets so you don''t lose money if the visa is rejected.', 'Have you booked your flights yet, or would you like tips on booking?', 7),
('germany', 'schengen_tourist', 'travel', 'accommodation', 'Accommodation Proof', 'Hotel reservations or invitation letter from host for entire duration of stay', null, 'You need proof of where you''ll stay each night. Hotel bookings from Booking.com (with free cancellation) work perfectly. If staying with someone, they need to provide an invitation letter.', 'Where are you planning to stay? Hotel, Airbnb, or with someone you know?', 8),
('germany', 'schengen_tourist', 'travel', 'itinerary', 'Travel Itinerary', 'Day-by-day travel plan showing cities, activities, and transportation', null, 'A simple day-by-day plan showing what you''ll do each day. It doesn''t have to be rigid — just shows the consulate you have a genuine travel plan.', 'Which cities do you plan to visit, and for how many days each?', 9),
('germany', 'schengen_tourist', 'personal', 'employment_letter', 'Employment Letter', 'Letter from employer confirming position, salary, leave approval, and return guarantee', null, 'Ask your HR for a letter stating your position, salary, that leave is approved, and that you will return after the trip. If self-employed, a CA letter confirming your business works.', 'Are you currently employed? Can your employer provide a letter confirming your leave?', 10),
('germany', 'schengen_tourist', 'personal', 'leave_approval', 'Leave Approval', 'Written leave approval from employer for the travel dates', null, 'This can be part of the employment letter or a separate leave sanction document. Make sure the dates match your travel dates.', null, 11);

-- France: Schengen Tourist Visa requirements
insert into visa_requirements (country, visa_type, category, requirement_key, title, description, threshold, recommendation, question_hint, display_order) values
('france', 'schengen_tourist', 'financial', 'bank_balance', 'Bank Balance', 'Minimum bank balance of 6 lakh INR maintained for last 3 months (France tends to require slightly higher proof)', '600000', 'France consulates typically look for slightly higher financial proof — around 6 lakh INR or more. Fixed deposits and property papers can supplement if your savings are lower.', 'How much balance do you currently have in your bank account?', 1),
('france', 'schengen_tourist', 'financial', 'income_proof', 'Income Proof', 'Salary slips for last 3 months or ITR for last 3 years (France requires 3 years)', null, 'France asks for 3 years of ITR (not 2 like most Schengen countries). Make sure you have ITR acknowledgements for the last 3 financial years.', 'Are you salaried or self-employed? Do you have ITR for the last 3 years?', 2),
('france', 'schengen_tourist', 'documents', 'passport_validity', 'Passport Validity', 'Passport must be valid for at least 3 months beyond return date with 2 blank pages', null, 'Same as other Schengen countries — 3 months validity beyond return and 2 blank pages required.', 'When does your current passport expire?', 3),
('france', 'schengen_tourist', 'documents', 'passport_photos', 'Passport Photos', '2 recent passport photos (35mm x 45mm, white background)', null, 'Standard Schengen photo specs — 35x45mm, white background, taken within last 6 months.', 'Do you have recent passport photos?', 4),
('france', 'schengen_tourist', 'documents', 'cover_letter', 'Cover Letter', 'Letter explaining purpose of visit, in English or French', null, 'I can generate this for you. France accepts English cover letters, though a French version is appreciated.', null, 5),
('france', 'schengen_tourist', 'documents', 'travel_insurance', 'Travel Insurance', 'Minimum 30,000 EUR coverage, valid in all Schengen states', '30000', 'Same requirement as all Schengen countries — 30,000 EUR minimum medical coverage.', 'Do you have travel insurance arranged?', 6),
('france', 'schengen_tourist', 'travel', 'flight_booking', 'Flight Booking', 'Confirmed round-trip flight reservation', null, 'Book refundable tickets or use a hold service. Make sure the return date is within 90 days of entry.', 'Have you booked your flights?', 7),
('france', 'schengen_tourist', 'travel', 'accommodation', 'Accommodation Proof', 'Hotel bookings or attestation d''accueil (hosting certificate) if staying with someone', null, 'France has a specific form called "attestation d''accueil" if you''re staying with a host — they need to get it from their local mairie (town hall). Hotel bookings are simpler.', 'Where will you be staying in France?', 8),
('france', 'schengen_tourist', 'travel', 'itinerary', 'Travel Itinerary', 'Detailed day-by-day plan with intercity transport if visiting multiple cities', null, 'If visiting multiple French cities, show how you''ll travel between them (train tickets, etc).', 'Which cities in France do you plan to visit?', 9),
('france', 'schengen_tourist', 'personal', 'employment_letter', 'Employment Letter', 'Letter from employer on company letterhead confirming employment, salary, and approved leave', null, 'Must be on official letterhead with company stamp. Include your join date, designation, salary, and approved leave dates.', 'Can your employer provide a letter on letterhead?', 10),
('france', 'schengen_tourist', 'personal', 'noc_from_employer', 'No Objection Certificate', 'Some France consulates require a separate NOC from employer', null, 'This varies by consulate location. The VFS France center in your city can confirm if they need it separately from the employment letter.', 'Which city will you be applying from?', 11);
